services:
  app:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      OAuth__JwtSigningKey: "eEdftrhRLXXgTXvxPwmuvdkmxVhPJec22GJrMAnUv6YuZpuBsjv4bCT5TZAnrjsv"

    ports:
      - "127.0.0.1:5000:5000"
