// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XamantaSDK.Data;

#nullable disable

namespace XamantaSDK.Data.Migrations
{
    [DbContext(typeof(XamantaDbContext))]
    partial class XamantaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("XamantaSDK.Data.Entities.AuthAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Successful")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("ClientId");

                    b.ToTable("AuthAttempts");
                });

            modelBuilder.Entity("XamantaSDK.Data.Entities.Client", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedScopes")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnrollmentId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("XamantaSDK.Data.Entities.ComplianceReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Compliance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ReceivedAt");

                    b.ToTable("ComplianceReports");
                });

            modelBuilder.Entity("XamantaSDK.Data.Entities.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedPolicyName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AppliedPolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastComplianceAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastComplianceStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastContactAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSentPolicyName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastSentPolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncInfoJson")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("XamantaSDK.Data.Entities.Enrollment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ActivationCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedScopes")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxActivations")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Selector")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifierHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Selector")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("XamantaSDK.Data.Entities.IssuedToken", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Jti");

                    b.HasIndex("ClientId");

                    b.HasIndex("IssuedAt");

                    b.ToTable("IssuedTokens");
                });

            modelBuilder.Entity("XamantaSDK.Data.Entities.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("XamantaSDK.Data.Entities.Client", b =>
                {
                    b.HasOne("XamantaSDK.Data.Entities.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("XamantaSDK.Data.Entities.IssuedToken", b =>
                {
                    b.HasOne("XamantaSDK.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
